"""initial

Revision ID: 7e8e2b8ceb85
Revises: 
Create Date: 2026-04-03 17:54:22.640343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8e2b8ceb85'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lemmas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('devanagari', sa.String(), nullable=False),
    sa.Column('romanized', sa.String(), nullable=False),
    sa.Column('part_of_speech', sa.String(), nullable=False),
    sa.Column('gender', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('devanagari')
    )
    op.create_table('stories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('title_hi', sa.String(), nullable=False),
    sa.Column('author', sa.String(), nullable=False),
    sa.Column('source_url', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('magic_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('sentences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('sequence_num', sa.Integer(), nullable=False),
    sa.Column('devanagari', sa.Text(), nullable=False),
    sa.Column('romanized', sa.Text(), nullable=False),
    sa.Column('english', sa.Text(), nullable=False),
    sa.Column('audio_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('word_senses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('lemma_id', sa.UUID(), nullable=False),
    sa.Column('english_definition', sa.Text(), nullable=False),
    sa.Column('usage_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lemma_id'], ['lemmas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookmarks',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('story_id', sa.UUID(), nullable=False),
    sa.Column('sentence_id', sa.UUID(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'story_id'),
    sa.UniqueConstraint('user_id', 'story_id', name='uq_bookmark_user_story')
    )
    op.create_table('sentence_words',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('sentence_id', sa.UUID(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('surface_devanagari', sa.String(), nullable=False),
    sa.Column('surface_romanized', sa.String(), nullable=False),
    sa.Column('english_gloss', sa.String(), nullable=False),
    sa.Column('lemma_id', sa.UUID(), nullable=True),
    sa.Column('word_sense_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['lemma_id'], ['lemmas.id'], ),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['word_sense_id'], ['word_senses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_sentence_reads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sentence_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sentence_id'], ['sentences.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_word_reads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('sentence_word_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sentence_word_id'], ['sentence_words.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_word_reads')
    op.drop_table('user_sentence_reads')
    op.drop_table('sentence_words')
    op.drop_table('bookmarks')
    op.drop_table('word_senses')
    op.drop_table('sentences')
    op.drop_table('magic_links')
    op.drop_table('users')
    op.drop_table('stories')
    op.drop_table('lemmas')
    # ### end Alembic commands ###
